spring:
  application:
    name: notification-service-dev

  datasource:
    url: jdbc:h2:mem:notification_dev_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

resilience4j:
  retry:
    instances:
      notificationDeliveryRetry:
        max-attempts: 3
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - com.demo.notification.exception.TransientProviderException
        ignore-exceptions:
          - com.demo.notification.exception.PermanentProviderException

notification:
  auto-dispatch:
    enabled: true


